### ISSUE TITLE
Questions about data to replicate ppi-variant-tracker

### ISSUE THREAD

**Issue by vikram-sridharan-concentric** [PandemicPreventionInstitute/ppi-variant-tracker-manuscript#5]
Hello @zsusswein & @kaitejohnson 

I am trying to replicate your historical validation based on your instructions. Since the reference datasets are missing I am trying find way to get GISAID data myself from their portal and use that to replicate your backtesting.

`code/auto_extract_gisaid.R` - references a specific tar file export from GISAID. Since I don't have that I sourced all sequence data from GISAID for the date range April 28th, 2022 and July 1st, 2022 and wrote that to `../data/raw/2022-07-01_metadata.csv`

Could you please advice what `reference_data_df.csv` refers to?

Are there a sequence of steps in your code base to generate the rest of the data needed to replicate the backtesting?

Thanks for your help.
 
In `pre_processing_HV.R` you reference `

`For the 6 reference datasets, we manually time stamped these corresponding to the day they were generated. These are saved into ../data/raw/{reference_date}_metadata.csv. Alternatively, generate these from filtering the current metadata by submission date, for each reference date.`

`
auto_extract_gisaid.R

write_csv(gisaid_metadata, '../data/raw/metadata.csv')`

`
pre_processing_HV.R

if (USE_CASE == 'local'){
  REFERENCE_DATA_PATH <- '../data/processed/reference_data_df.csv'
}

reference_data_df <- read_csv(REFERENCE_DATA_PATH)

# Filter the dates we want to actually use
dates_list <-ymd(c("2022-04-30", "2022-05-16", "2022-05-27",
               "2022-06-04", "2022-06-27", "2022-07-01"))

reference_data_df <- reference_data_df %>% filter(reference_date %in% dates_list)`

**Comment by kaitejohnson** [comment]
Thanks for flagging. We just added the `reference_data_df.csv` to the repo. This contains the date that we pulled the metadata (reference_date), the last submission date in that data set (last_submission_date) and the last collection date in that dataset (last_collection_date). If the pango lineage assignments were constant, you could simply use the last submission date to parse the current data to recreate the data as it was observed on those days. 

Regarding running the model using the time-stamped metadata, please feel free to email us directly ([kjohnson@rockfound.org](mailto:kjohnson@rockfound.org) & [zsusswein@rockfound.org](mailto:zsusswein@rockfound.org)).

**Comment by zsusswein** [comment]
Hey @vikram-sridharan-concentric -- I'm closing this out, given that the problem seems to be resolved per our conversations here and over email. If you have any more issues, feel free to send another email or re-open this issue.

**Comment by vikram-sridharan-concentric** [comment]
Hi @kaitejohnson @zsusswein - Thank you for all your help.
